package(default_visibility = ["//visibility:public"])

# TODO(bolitt): To add ios examples in future.
#
# ios_static_framework(
#     name = "HelloLib.framework",
#     hdrs = [":HelloLib.objc.hdrs"],
#     bundle_name = "HelloLib",
#     families = [
#         "iphone",
#         "ipad",
#     ],
#     minimum_os_version = "10.0",
#     deps = [":HelloLib.objc"],
# )
